"""create table

Revision ID: d467a7d214eb
Revises: d3567ffa537e
Create Date: 2025-01-14 21:21:11.097713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd467a7d214eb'
down_revision: Union[str, None] = 'd3567ffa537e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'return_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'return_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
